version: '3.5'

networks:
  default:
    driver: bridge

services:
  nginx-load-balancer:
    build:
      context: ./load-balancer
    volumes:
    - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    networks:
      - default

  node1:
    image: nginx:latest
    volumes:
      - ./node/nginx.conf:/etc/nginx/nginx.conf
      - ./cache/node1:/usr/share/nginx/cache
    ports:
      - 80
    networks:
      - default

  node2:
    image: nginx:latest
    volumes:
      - ./node/nginx.conf:/etc/nginx/nginx.conf
      - ./cache/node2:/usr/share/nginx/cache
    ports:
      - 80
    networks:
      - default

  node3:
    image: nginx:latest
    volumes:
      - ./node/nginx.conf:/etc/nginx/nginx.conf
      - ./cache/node3:/usr/share/nginx/cache
    ports:
      - 80
    networks:
      - default
